---
branches:
  only:
    - master
language: ruby
before_install: 'bundle install'
script: bundle exec rake SPEC_OPTS='--format documentation'
rvm:
  - 1.9.3
  - 2.0.0
gemfile: Gemfile
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.7.1"
matrix:
  include:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.3.0"
notifications:
  email: false
